### ISSUE TITLE
mount: build: mount point does not exist.

### ISSUE THREAD

**Issue by DimitryVo** [ClemaX/ft_linux#2] opened 2023-06-03 13:05 UTC
Hello, thank you for your help, now I see next error:

mount: /dev bound on /mnt/lfs/dev.
mount: /dev/pts bound on /mnt/lfs/dev/pts.
mount: proc mounted on /mnt/lfs/proc.
mount: sysfs mounted on /mnt/lfs/sys.
mount: tmpfs mounted on /mnt/lfs/run.
mount: /cache bound on /mnt/lfs/cache.
mount: /tmp bound on /mnt/lfs/tmp.
mount: build: mount point does not exist.
error_handler: /root/utils/lfs_chroot.sh:95: mount -v --bind /root/chroot build returned with unexpected exit status 0
exit_handler: Cleaning up...
/mnt/lfs is a mountpoint
error_handler: /root/utils/lfs_chroot.sh:37: mount -v --bind /root/chroot build returned with unexpected exit status 0

Could you recommend anything?

**Comment by ClemaX** [comment] 2023-06-03 14:02
Hi, are you sure that you're on the latest commit of the master branch?
This should have been fixed in commit `9a05823f77786e6c70d65e1b6d051e2c00e882a4`.

Please check that you're on the latest commit of the master branch. The command
```sh
git show-ref --verify refs/heads/main
```
should output:
```
056c69b61ca38bf3e09483d2af14d8371d494ac8 refs/heads/main
```

If you are on the latest commit, the issue may be caused by the cached docker image's contents being outdated. In this case please report back for troubleshooting.

**Comment by DimitryVo** [comment] 2023-06-03 14:40
Hi, thank you for your answer. I have tried to use latest version, success checked commit by you recommendation, but after run "sudo make all" get error:

 => exporting to image                                                                                                                                                                 0.0s
 => => exporting layers                                                                                                                                                                0.0s
 => => writing image sha256:dd39665e56800d242b5c6cf3fa82220d858751d673ff0c697d41f0046be0f8ad                                                                                           0.0s
 => => naming to docker.io/library/ft_linux                                                                                                                                            0.0s
**/bin/sh: 4: set: Illegal option -o pipefail
make: *** [Makefile:60: dist/lfs.img] Error 2**

For resolve I add "SHELL=/bin/bash" to start of Makefile

**Comment by ClemaX** [comment] 2023-06-03 15:01
Oh, I don't understand why the image is broken now. The `/bin/sh` seems to be linked to `/bin/dash` (the default) instead of the required `/bin/bash`. Please ensure that the git tree is clean (`git status`) and try to rebuild the docker image. There are some other issues due to outdated sources. I will fix this this week-end but it may take a few days.

**Comment by DimitryVo** [comment] 2023-06-03 15:09
I have removed all docker images and I have tried rebuild. And now I see:

md5sum: nss-3.89-standalone-1.patch: No such file or directory
md5sum: firefox-102.10.0-upstream_fixes-1.patch: No such file or directory
md5sum: firefox-102.10.0-ffmpeg_6-1.patch: No such file or directory
md5sum: nss-3.89-standalone-1.patch: No such file or directory
md5sum: firefox-102.10.0-upstream_fixes-1.patch: No such file or directory
md5sum: firefox-102.10.0-ffmpeg_6-1.patch: No such file or directory
md5sum: WARNING: 3 listed files could not be read
0% 0:3=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                               https://www.linuxfromscratch.org/patches/blfs/svn/nss-3.89-standalone-1.patch:
2023-06-03 15:06:16 ERROR 404: Not Found.
33% 1:2=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                              https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-upstream_fixes-1.patch:
2023-06-03 15:06:16 ERROR 404: Not Found.
66% 2:1=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                              https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch:
2023-06-03 15:06:16 ERROR 404: Not Found.
100% 3:0=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                             
sources_fetch_list: Warning: 3 jobs failed!
md5sum: nss-3.89-standalone-1.patch: No such file or directory
md5sum: firefox-102.10.0-upstream_fixes-1.patch: No such file or directory
md5sum: firefox-102.10.0-ffmpeg_6-1.patch: No such file or directory
md5sum: WARNING: 3 listed files could not be read
md5sum: nss-3.89-standalone-1.patch: No such file or directory
md5sum: firefox-102.10.0-upstream_fixes-1.patch: No such file or directory
md5sum: firefox-102.10.0-ffmpeg_6-1.patch: No such file or directory
md5sum: WARNING: 3 listed files could not be read
0% 0:3=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                               https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-upstream_fixes-1.patch:
2023-06-03 15:06:22 ERROR 404: Not Found.
33% 1:2=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                              https://www.linuxfromscratch.org/patches/blfs/svn/nss-3.89-standalone-1.patch:
2023-06-03 15:06:22 ERROR 404: Not Found.
66% 2:1=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                              https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch:
2023-06-03 15:06:22 ERROR 404: Not Found.
100% 3:0=0s https://www.linuxfromscratch.org/patches/blfs/svn/firefox-102.10.0-ffmpeg_6-1.patch                                                                                             
error_handler: /root/utils/sources.sh:52: "${parallel_cmd[@]}" "${wget_cmd[@]}" returned with unexpected exit status 0
error_handler: /root/utils/sources.sh:141: parallel_fetch --no-clobber returned with unexpected exit status 0
 
We need change firefox-102.10.0 to firefox-102.11.0, nss-3.89 to nss-3.89.1 and update md5(

**Comment by ClemaX** [comment] 2023-06-04 13:13
Hi, some patch files have been moved or updated recently, because I used some packages versions from the development BLFS branch (svn). I will include the missing files in this repository and eventually replace them with stable versions. The main reason I used these development versions was to provide a more recent version of the firefox browser.

**Comment by ClemaX** [comment] 2023-06-05 13:01
I have replaced the problematic patches and updated glib, nss, firefox and mesa. I'm currently rebuilding to see if everything is fine. I'll let you know when it's done.

**Comment by ClemaX** [comment] 2023-06-05 15:20
I just completed the rebuild with success, please let me know if you still encounter some issues.

**Closed as completed by ClemaX** 2023-06-05 15:20 UTC
